# Generated by Django 4.2 on 2025-10-20 19:50

from django.db import migrations, models
import donors.models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='badge_icon',
            field=models.ImageField(blank=True, help_text='Badge icon image', null=True, upload_to=donors.models.achievement_badge_path),
        ),
        migrations.AlterField(
            model_name='donationhistory',
            name='certificate',
            field=models.FileField(blank=True, help_text='Upload donation certificate (PDF, JPG, PNG)', null=True, upload_to=donors.models.donation_certificate_path),
        ),
    ]
