# Generated by Django 5.2.5 on 2025-10-14 14:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0002_remove_donor_donor_id_donor_id_alter_donor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=200)),
                ('requester_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('units_required', models.PositiveIntegerField(default=1)),
                ('date_needed', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('urgency', models.CharField(choices=[('High', 'High'), ('Normal', 'Normal')], default='Normal', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='request_proofs/')),
                ('fulfilled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_donor', models.ForeignKey(blank=True, help_text='Optional: link to a donor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='donors.donor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodrequests.hospital')),
            ],
            options={
                'ordering': ['-urgency', 'date_needed', '-created_at'],
            },
        ),
    ]
