# Generated by Django 5.2.7 on 2025-10-16 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled'), ('closed', 'Closed')], default='open', max_length=15)),
                ('is_emergency', models.BooleanField(default=False)),
                ('location', models.CharField(choices=[('campus', 'UAP Campus'), ('uttara', 'Uttara'), ('gulshan', 'Gulshan'), ('banani', 'Banani'), ('dhanmondi', 'Dhanmondi'), ('mirpur', 'Mirpur')], max_length=20)),
                ('needed_by_date', models.DateTimeField()),
                ('units_required', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='request_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.bloodgroup')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_request', 'New Blood Request'), ('matched', 'Request Matched'), ('fulfilled', 'Request Fulfilled'), ('achievement', 'New Achievement'), ('response', 'Response to Your Request')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='requests.bloodrequest')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.donor')),
            ],
            options={
                'unique_together': {('blood_request', 'donor')},
            },
        ),
    ]
